title: Zindagi Na Mile Doobara
author: Rishabh Mishra
email: rishabhmishra1729@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome Guys! Now you are about to know my journey 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
